@startuml
start
:启动;
:判断时间;
if(时间处于10 - 12 && 14-19) then(yes)
    :开始运行;
    :进入循环;
    while(满足时间条件?)
        :生成[30-40]随机时间;
        :开始计时;
        :时间结束提醒移动;
    endwhile
    :弹出提示;
    end
else (no)
    :弹出提示;
    end
@enduml